print("Welcome to Band Name Genrator")
print("What's the name of city you grew up in?")
city = input()
print("What's your pet's name?")
name = input()
print("Your band name could be "+ city + " " + name)
